@startuml  data
skinparam maxMessageSize 70
' 你可以使用 ||| 来增加空间。
' 还可以使用数字指定增加的像素的数量。
{start} Alice -> Bob: message 1
{data} Bob --> Alice: ok
{start} <-> {data}
|||
Alice -> Bob: message 2
Bob --> Alice: ok
||45||
Alice -> Bob: message 3
== 分隔符 ==
Bob --> Alice: ok
@enduml