
:toc:

:icons: font

// 保证所有的目录层级都可以正常显示图片
:path: instruction/
:imagesdir: ../image/
:srcdir: ../src


// 只有book调用的时候才会走到这里
ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
:srcdir: {rootpath}../src/
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ../
:srcdir: {rootpath}{path}../src/
endif::rootpath[]

== 引言

=== 特性

* Keys 和 values 可以是任意长度的数组
* 数据按照key值进行存储.
* 用户可以根据需要提供一个对比函数来实现对Key值的排序
* 向外提供了 `Put(key,value)`, `Get(key)`, `Delete(key)` 等接口
* 支持事务
* 用户可以创建快照
* 支持按照迭代器遍历数据
* https://google.github.io/snappy[数据库会自动使用Snappy库对数据进行压缩]
* 很多接口都是提供的虚函数，用户可以根据自己的需要进行替换

=== 限制

- 请注意，levelDB并不是一个SQL数据库，并不对外提供关系型数据模型，也不支持SQL语句，也同样不支持索引
- 在多线程程序中数据库不支持并发操作，同一时间只支持一个线程进行访问
- 数据库不支持cs模型，如果用户需要使用cs模型，需要用户自行进行封装。


=== 文件说明

对外提供的文件全部都在 `include/leveldb/` 里面，用户不应该使用除了该目录之外的任何头文件

* **include/leveldb/db.h**: 主头文件，使用levelDB必不可少
* **include/leveldb/options.h**: 数据库操作选项，用来控制整个数据库或者数据库的读写过程
* **include/leveldb/comparator.h**:  比较器抽象接口，默认按照字节序进行对比，用户可以根据需要编写自己的比较器。
* **include/leveldb/iterator.h**: 用于迭代数据的迭代器，该迭代器可以在DB对象中获取
* **include/leveldb/write_batch.h**: 原子操作接口，用来实现数据库对事务的支持。
* **include/leveldb/slice.h**: 一个数据切片的简单实现
* **include/leveldb/status.h**: 状态对象，用于对外接口返回，可以通过状态查看返回状态是成功、失败或者是其他错误
* **include/leveldb/env.h**: 系统环境抽象接口
* **include/leveldb/table.h, include/leveldb/table_builder.h**:  数据库底层接口，大部分用户基本上用不到该功能。

=== 打开一个数据库

使用 `static Status Open(const Options &options, const std::string &name, DB **dbptr)` 可以打开一个数据库， options填入数据库打开选项，name指定数据库名，DB给出一个数据库指针(原先指向nullptr)，因为调用之后会把创建的数据库句柄赋值给对应的指针。

- Options 用来控制数据库行为的一些参数在调用 `DB::Open` 的时候使用，下面是Options的说明

[source,c++]
----
struct LEVELDB_EXPORT Options {
    // 使用默认值构造Options
    Options();
    // Comparator 用来定义keys值在table中的排序方式
    // Default: 默认提供的对比工具是按照字典顺序进行排序的，也就是字典中字幕的排列顺序进行排序
    // 需要用户保证所有打开数据的对比工具都是一致的
    const Comparator *comparator;
    // 如果设置为true，当数据库丢失时会创建一个新的数据库
    bool create_if_missing = false;
    // 如果设置为true，当同名数据库已经存在就直接报错
    bool error_if_exists = false;
    // 如果设置为true，将会实现对正在设置的数据进行检查，如果检测到任何错误将会提前停止
    // 这可能会导致不可预料的异常，例如：一个损坏的DB表项，可能造成大量的DB表项不可读
    // 甚至导致整个数据库不可打开
    bool paranoid_checks = false;
    // 一些和使用的平台相关的操作，如：读写文件操作
    // Default: Env::Default()
    Env *env;
    // 如果该句柄非空，DB中发生的任何错误都会记录到info_log句柄中，日志会在DB同样的目录里面创建
    // 一个日志文件用来存储日志记录
    Logger *info_log = nullptr;
    // -------------------
    // Parameters that affect performance
    // 写缓存大小，越大速度越快，在内存中存储的数据是无序的，当进行落盘的时候需要转化为有序
    // 状态。一个大的写缓存可能会导致比较长的数据库恢复时间
    size_t write_buffer_size = 4 * 1024 * 1024;
    // 数据库允许打开文件的最大数量，当你预估数据库存储的内容可能会很大时，可以根据需要适当增大该值
    // 进行预算时，按照每2M内容一个文件来进行预算
    int max_open_files = 1000;
    // 控制blocks，DB会将用户的数据存储成一系列的blocks，一个block是一个从磁盘中加载的单元
    // 如果非空，会使用用户指定的Cache，如果为空，levelDB会创建一个默认的8M的内部Cache
    Cache *block_cache = nullptr;
    // 用来指定每个block用户数据的大小，这些大小都是数据压缩之前的大小
    // 当压缩之后存储在磁盘上的数据可能远小于这个值的大小(如果启用了压缩功能)，该值可以根据需要动态的进行改变
    size_t block_size = 4 * 1024;
    //在 LevelDB 中，block_restart_interval 是用于控制块重启的变量。LevelDB 使用块（block）来组织和存储数据，
    // 每个块是一个数据块，包含多个键值对。block_restart_interval 确定了在块中重新启动（restart）前的连续键值对的数量。
    //在 LevelDB 的块中，每个重新启动点都需要存储键的前缀，这样可以在搜索和查找操作中更快地定位到特定的键。
    // 重新启动点是为了减少在每个键值对中存储完整键的开销。
    //block_restart_interval 变量定义了在一个块中连续键值对的数量。
    // 当达到 block_restart_interval 时，LevelDB 将创建一个新的重新启动点，并存储相应的键前缀。
    // 这样，在进行查找时，LevelDB 可以根据重新启动点的位置快速定位到特定的键。
    //通过调整 block_restart_interval 的值，可以在性能和空间消耗之间进行权衡。
    // 大部分客户可能用不到该值
    int block_restart_interval = 16;
    // leveldb会创建文件用于记录数据，该值制定了每个文件的大小，在每次将要超过该值时，levelDB会创建新的文件
    // 大部分客户端应该保持改制不变，但是当你的系统对大文件更加高效的时候，你应该考虑适当的增加该值的大小
    size_t max_file_size = 2 * 1024 * 1024;
    // 用来指定压缩算法，可以动态修改
    // 默认: kSnappyCompression压缩算法，能给出极速但是轻量级压缩.
    CompressionType compression = kSnappyCompression;
    bool reuse_logs = false;
    // 使用指定的过滤条件，来讲减少对磁盘的访问(设置为NewBloomFilterPolicy之后，能很大程度的减少对磁盘的访问次数)
    // NewBloomFilterPolicy()
    const FilterPolicy *filter_policy = nullptr;
};
----

- 第二个 `const std::string & name` 用来指定数据库目录名称，leveldb数据库会在该文件夹中创建一些列数据。
- 第三个参数 `DB **dbptr` 是打开成功之后的数据库句柄，后期对于数据库的一切操作都经过该句柄进行

在了解了这些之后，我们就可以着手使用 `DB::Open()` 来打开一个数据库了。

[source,c++]
----
#include <cassert>
#include "leveldb/db.h"
// 定义一个数据库句柄
leveldb::DB* db = nullptr;
leveldb::Options options;
options.create_if_missing = true;
leveldb::Status status = leveldb::DB::Open(options, "/tmp/testdb", &db);
assert(status.ok());
...
----

如果你想数据库存在就报错，可以在打开数据库之前设置以下值为true

[source, cpp]
----
options.error_if_exists = true;
----

=== 执行结果 Status

在levelDB中你随处可见Status，该对象就是levelDB对返回值进行封装时候的结果，用来返回各种接口的执行情况

[source, cpp]
----
leveldb::Status s = ...;
if (!s.ok()) cerr << s.ToString() << endl;
----


== 如何关闭一个levelDB数据库

当想关闭一个levelDB数据库时只需要调用delete将db删除即可。

[source,c++]
----
... open the db as described above ...
... do something with db ...
delete db;
----

== 数据库的读写

levelDB提供了Put/Delete/Get等接口来对数据库进行操作。

[source,c++]
----
std::string value;
// 1. 去除key1的值
leveldb::Status s = db->Get(leveldb::ReadOptions(), key1, &value);
// 将key2的值设置为key1的值
if (s.ok()) s = db->Put(leveldb::WriteOptions(), key2, value);
// 删除key1
if (s.ok()) s = db->Delete(leveldb::WriteOptions(), key1);
----

== 原子操作(事务类型)

[listing]
....
上述将Key1的值设置给key2并删除Key1总共经过了三步，如果在删除key1之前数据库崩溃或被强制停掉了就会导致value存在key1和key2中。为了避免这种异常情况的出现，我们可以将上述三种情况作为一个原子操作。levelDB中可以通过WriteBatch来实现对多个步骤进行原子操作
....

[source,c++]
----
#include "leveldb/write_batch.h"
...
std::string value;
leveldb::Status s = db->Get(leveldb::ReadOptions(), key1, &value);
if (s.ok()) {
  leveldb::WriteBatch batch;
  batch.Delete(key1);
  batch.Put(key2, value);
  s = db->Write(leveldb::WriteOptions(), &batch);
}
----

The `WriteBatch` holds a sequence of edits to be made to the database, and these
edits within the batch are applied in order.Note that we called Delete before
Put so that if key1 is identical to key2, we do not end up erroneously dropping
the value entirely.

Apart from its atomicity benefits, `WriteBatch` may also be used to speed up
bulk updates by placing lots of individual mutations into the same batch.

## Synchronous Writes

By default, each write to leveldb is asynchronous: it returns after pushing the
write from the process into the operating system. The transfer from operating
system memory to the underlying persistent storage happens asynchronously. The
sync flag can be turned on for a particular write to make the write operation
not return until the data being written has been pushed all the way to
persistent storage. (On Posix systems, this is implemented by calling either
`fsync(...)` or `fdatasync(...)` or `msync(..., MS_SYNC)` before the write
operation returns.)

```c++
leveldb::WriteOptions write_options;
write_options.sync = true;
db->Put(write_options, ...);
```

Asynchronous writes are often more than a thousand times as fast as synchronous
writes. The downside of asynchronous writes is that a crash of the machine may
cause the last few updates to be lost. Note that a crash of just the writing
process (i.e., not a reboot) will not cause any loss since even when sync is
false, an update is pushed from the process memory into the operating system
before it is considered done.

Asynchronous writes can often be used safely. For example, when loading a large
amount of data into the database you can handle lost updates by restarting the
bulk load after a crash. A hybrid scheme is also possible where every Nth write
is synchronous, and in the event of a crash, the bulk load is restarted just
after the last synchronous write finished by the previous run. (The synchronous
write can update a marker that describes where to restart on a crash.)

`WriteBatch` provides an alternative to asynchronous writes. Multiple updates
may be placed in the same WriteBatch and applied together using a synchronous
write (i.e., `write_options.sync` is set to true). The extra cost of the
synchronous write will be amortized across all of the writes in the batch.

## Concurrency

A database may only be opened by one process at a time. The leveldb
implementation acquires a lock from the operating system to prevent misuse.
Within a single process, the same `leveldb::DB` object may be safely shared by
multiple concurrent threads. I.e., different threads may write into or fetch
iterators or call Get on the same database without any external synchronization
(the leveldb implementation will automatically do the required synchronization).
However other objects (like Iterator and `WriteBatch`) may require external
synchronization. If two threads share such an object, they must protect access
to it using their own locking protocol. More details are available in the public
header files.

## Iteration

The following example demonstrates how to print all key,value pairs in a
database.

```c++
leveldb::Iterator* it = db->NewIterator(leveldb::ReadOptions());
for (it->SeekToFirst(); it->Valid(); it->Next()) {
  cout << it->key().ToString() << ": "  << it->value().ToString() << endl;
}
assert(it->status().ok());  // Check for any errors found during the scan
delete it;
```

The following variation shows how to process just the keys in the range
[start,limit):

```c++
for (it->Seek(start);
   it->Valid() && it->key().ToString() < limit;
   it->Next()) {
  ...
}
```

You can also process entries in reverse order. (Caveat: reverse iteration may be
somewhat slower than forward iteration.)

```c++
for (it->SeekToLast(); it->Valid(); it->Prev()) {
  ...
}
```

## Snapshots

Snapshots provide consistent read-only views over the entire state of the
key-value store.  `ReadOptions::snapshot` may be non-NULL to indicate that a
read should operate on a particular version of the DB state. If
`ReadOptions::snapshot` is NULL, the read will operate on an implicit snapshot
of the current state.

Snapshots are created by the `DB::GetSnapshot()` method:

```c++
leveldb::ReadOptions options;
options.snapshot = db->GetSnapshot();
... apply some updates to db ...
leveldb::Iterator* iter = db->NewIterator(options);
... read using iter to view the state when the snapshot was created ...
delete iter;
db->ReleaseSnapshot(options.snapshot);
```

Note that when a snapshot is no longer needed, it should be released using the
`DB::ReleaseSnapshot` interface. This allows the implementation to get rid of
state that was being maintained just to support reading as of that snapshot.

## Slice

The return value of the `it->key()` and `it->value()` calls above are instances
of the `leveldb::Slice` type. Slice is a simple structure that contains a length
and a pointer to an external byte array. Returning a Slice is a cheaper
alternative to returning a `std::string` since we do not need to copy
potentially large keys and values. In addition, leveldb methods do not return
null-terminated C-style strings since leveldb keys and values are allowed to
contain `'\0'` bytes.

C++ strings and null-terminated C-style strings can be easily converted to a
Slice:

```c++
leveldb::Slice s1 = "hello";

std::string str("world");
leveldb::Slice s2 = str;
```

A Slice can be easily converted back to a C++ string:

```c++
std::string str = s1.ToString();
assert(str == std::string("hello"));
```

Be careful when using Slices since it is up to the caller to ensure that the
external byte array into which the Slice points remains live while the Slice is
in use. For example, the following is buggy:

```c++
leveldb::Slice slice;
if (...) {
  std::string str = ...;
  slice = str;
}
Use(slice);
```

When the if statement goes out of scope, str will be destroyed and the backing
storage for slice will disappear.

## Comparators

The preceding examples used the default ordering function for key, which orders
bytes lexicographically. You can however supply a custom comparator when opening
a database.  For example, suppose each database key consists of two numbers and
we should sort by the first number, breaking ties by the second number. First,
define a proper subclass of `leveldb::Comparator` that expresses these rules:

```c++
class TwoPartComparator : public leveldb::Comparator {
 public:
  // Three-way comparison function:
  //   if a < b: negative result
  //   if a > b: positive result
  //   else: zero result
  int Compare(const leveldb::Slice& a, const leveldb::Slice& b) const {
    int a1, a2, b1, b2;
    ParseKey(a, &a1, &a2);
    ParseKey(b, &b1, &b2);
    if (a1 < b1) return -1;
    if (a1 > b1) return +1;
    if (a2 < b2) return -1;
    if (a2 > b2) return +1;
    return 0;
  }

  // Ignore the following methods for now:
  const char* Name() const { return "TwoPartComparator"; }
  void FindShortestSeparator(std::string*, const leveldb::Slice&) const {}
  void FindShortSuccessor(std::string*) const {}
};
```

Now create a database using this custom comparator:

```c++
TwoPartComparator cmp;
leveldb::DB* db;
leveldb::Options options;
options.create_if_missing = true;
options.comparator = &cmp;
leveldb::Status status = leveldb::DB::Open(options, "/tmp/testdb", &db);
...
```

### Backwards compatibility

The result of the comparator's Name method is attached to the database when it
is created, and is checked on every subsequent database open. If the name
changes, the `leveldb::DB::Open` call will fail. Therefore, change the name if
and only if the new key format and comparison function are incompatible with
existing databases, and it is ok to discard the contents of all existing
databases.

You can however still gradually evolve your key format over time with a little
bit of pre-planning. For example, you could store a version number at the end of
each key (one byte should suffice for most uses). When you wish to switch to a
new key format (e.g., adding an optional third part to the keys processed by
`TwoPartComparator`), (a) keep the same comparator name (b) increment the
version number for new keys (c) change the comparator function so it uses the
version numbers found in the keys to decide how to interpret them.

## Performance

Performance can be tuned by changing the default values of the types defined in
`include/options.h`.

### Block size

leveldb groups adjacent keys together into the same block and such a block is
the unit of transfer to and from persistent storage. The default block size is
approximately 4096 uncompressed bytes.  Applications that mostly do bulk scans
over the contents of the database may wish to increase this size. Applications
that do a lot of point reads of small values may wish to switch to a smaller
block size if performance measurements indicate an improvement. There isn't much
benefit in using blocks smaller than one kilobyte, or larger than a few
megabytes. Also note that compression will be more effective with larger block
sizes.

### Compression

Each block is individually compressed before being written to persistent
storage. Compression is on by default since the default compression method is
very fast, and is automatically disabled for uncompressible data. In rare cases,
applications may want to disable compression entirely, but should only do so if
benchmarks show a performance improvement:

```c++
leveldb::Options options;
options.compression = leveldb::kNoCompression;
... leveldb::DB::Open(options, name, ...) ....
```

### Cache

The contents of the database are stored in a set of files in the filesystem and
each file stores a sequence of compressed blocks. If options.block_cache is
non-NULL, it is used to cache frequently used uncompressed block contents.

```c++
#include "leveldb/cache.h"

leveldb::Options options;
options.block_cache = leveldb::NewLRUCache(100 * 1048576);  // 100MB cache
leveldb::DB* db;
leveldb::DB::Open(options, name, &db);
... use the db ...
delete db
delete options.block_cache;
```

Note that the cache holds uncompressed data, and therefore it should be sized
according to application level data sizes, without any reduction from
compression. (Caching of compressed blocks is left to the operating system
buffer cache, or any custom Env implementation provided by the client.)

When performing a bulk read, the application may wish to disable caching so that
the data processed by the bulk read does not end up displacing most of the
cached contents. A per-iterator option can be used to achieve this:

```c++
leveldb::ReadOptions options;
options.fill_cache = false;
leveldb::Iterator* it = db->NewIterator(options);
for (it->SeekToFirst(); it->Valid(); it->Next()) {
  ...
}
```

### Key Layout

Note that the unit of disk transfer and caching is a block. Adjacent keys
(according to the database sort order) will usually be placed in the same block.
Therefore the application can improve its performance by placing keys that are
accessed together near each other and placing infrequently used keys in a
separate region of the key space.

For example, suppose we are implementing a simple file system on top of leveldb.
The types of entries we might wish to store are:

    filename -> permission-bits, length, list of file_block_ids
    file_block_id -> data

We might want to prefix filename keys with one letter (say '/') and the
`file_block_id` keys with a different letter (say '0') so that scans over just
the metadata do not force us to fetch and cache bulky file contents.

### Filters

Because of the way leveldb data is organized on disk, a single `Get()` call may
involve multiple reads from disk. The optional FilterPolicy mechanism can be
used to reduce the number of disk reads substantially.

```c++
leveldb::Options options;
options.filter_policy = NewBloomFilterPolicy(10);
leveldb::DB* db;
leveldb::DB::Open(options, "/tmp/testdb", &db);
... use the database ...
delete db;
delete options.filter_policy;
```

The preceding code associates a Bloom filter based filtering policy with the
database.  Bloom filter based filtering relies on keeping some number of bits of
data in memory per key (in this case 10 bits per key since that is the argument
we passed to `NewBloomFilterPolicy`). This filter will reduce the number of
unnecessary disk reads needed for Get() calls by a factor of approximately
a 100. Increasing the bits per key will lead to a larger reduction at the cost
of more memory usage. We recommend that applications whose working set does not
fit in memory and that do a lot of random reads set a filter policy.

If you are using a custom comparator, you should ensure that the filter policy
you are using is compatible with your comparator. For example, consider a
comparator that ignores trailing spaces when comparing keys.
`NewBloomFilterPolicy` must not be used with such a comparator. Instead, the
application should provide a custom filter policy that also ignores trailing
spaces. For example:

```c++
class CustomFilterPolicy : public leveldb::FilterPolicy {
 private:
  FilterPolicy* builtin_policy_;

 public:
  CustomFilterPolicy() : builtin_policy_(NewBloomFilterPolicy(10)) {}
  ~CustomFilterPolicy() { delete builtin_policy_; }

  const char* Name() const { return "IgnoreTrailingSpacesFilter"; }

  void CreateFilter(const Slice* keys, int n, std::string* dst) const {
    // Use builtin bloom filter code after removing trailing spaces
    std::vector<Slice> trimmed(n);
    for (int i = 0; i < n; i++) {
      trimmed[i] = RemoveTrailingSpaces(keys[i]);
    }
    return builtin_policy_->CreateFilter(trimmed.data(), n, dst);
  }
};
```

Advanced applications may provide a filter policy that does not use a bloom
filter but uses some other mechanism for summarizing a set of keys. See
`leveldb/filter_policy.h` for detail.

## Checksums

leveldb associates checksums with all data it stores in the file system. There
are two separate controls provided over how aggressively these checksums are
verified:

`ReadOptions::verify_checksums` may be set to true to force checksum
verification of all data that is read from the file system on behalf of a
particular read.  By default, no such verification is done.

`Options::paranoid_checks` may be set to true before opening a database to make
the database implementation raise an error as soon as it detects an internal
corruption. Depending on which portion of the database has been corrupted, the
error may be raised when the database is opened, or later by another database
operation. By default, paranoid checking is off so that the database can be used
even if parts of its persistent storage have been corrupted.

If a database is corrupted (perhaps it cannot be opened when paranoid checking
is turned on), the `leveldb::RepairDB` function may be used to recover as much
of the data as possible

## Approximate Sizes

The `GetApproximateSizes` method can used to get the approximate number of bytes
of file system space used by one or more key ranges.

```c++
leveldb::Range ranges[2];
ranges[0] = leveldb::Range("a", "c");
ranges[1] = leveldb::Range("x", "z");
uint64_t sizes[2];
db->GetApproximateSizes(ranges, 2, sizes);
```

The preceding call will set `sizes[0]` to the approximate number of bytes of
file system space used by the key range `[a..c)` and `sizes[1]` to the
approximate number of bytes used by the key range `[x..z)`.

## Environment

All file operations (and other operating system calls) issued by the leveldb
implementation are routed through a `leveldb::Env` object. Sophisticated clients
may wish to provide their own Env implementation to get better control.
For example, an application may introduce artificial delays in the file IO
paths to limit the impact of leveldb on other activities in the system.

```c++
class SlowEnv : public leveldb::Env {
  ... implementation of the Env interface ...
};

SlowEnv env;
leveldb::Options options;
options.env = &env;
Status s = leveldb::DB::Open(options, ...);
```

## Porting

leveldb may be ported to a new platform by providing platform specific
implementations of the types/methods/functions exported by
`leveldb/port/port.h`.  See `leveldb/port/port_example.h` for more details.

In addition, the new platform may need a new default `leveldb::Env`
implementation.  See `leveldb/util/env_posix.h` for an example.

## Other Information

Details about the leveldb implementation may be found in the following
documents:

1. [Implementation notes](impl.md)
2. [Format of an immutable Table file](table_format.md)
3. [Format of a log file](log_format.md)

